-- MySQL Script generated by MySQL Workbench
-- Fri Aug 13 15:53:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`buyers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`buyers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`buyers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_card_number` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_card_number_UNIQUE` (`id_card_number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carriers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`carriers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`carriers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cid` VARCHAR(255) NOT NULL,
  `company_name` VARCHAR(255) NULL,
  `address` VARCHAR(255) NULL,
  `telephone` VARCHAR(255) NULL,
  `locality_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_carriers_localities1_idx` (`locality_id` ASC) VISIBLE,
  UNIQUE INDEX `cid_UNIQUE` (`cid` ASC) VISIBLE,
  CONSTRAINT `fk_carriers_localities1`
    FOREIGN KEY (`locality_id`)
    REFERENCES `mydb`.`localities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`countries` ;

CREATE TABLE IF NOT EXISTS `mydb`.`countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`employees` ;

CREATE TABLE IF NOT EXISTS `mydb`.`employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `card_number_id` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `warehouse_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employees_warehouse1_idx` (`warehouse_id` ASC) VISIBLE,
  UNIQUE INDEX `card_number_id_UNIQUE` (`card_number_id` ASC) VISIBLE,
  CONSTRAINT `fk_employees_warehouse1`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `mydb`.`warehouses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inbound_orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`inbound_orders` ;

CREATE TABLE IF NOT EXISTS `mydb`.`inbound_orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_date` DATETIME NULL,
  `order_number` VARCHAR(255) NULL,
  `employee_id` INT NOT NULL,
  `warehouse_id` INT NOT NULL,
  `product_batch_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_inbound_orders_employees1_idx` (`employee_id` ASC) VISIBLE,
  INDEX `fk_inbound_orders_warehouse1_idx` (`warehouse_id` ASC) VISIBLE,
  INDEX `fk_inbound_orders_product_batches1_idx` (`product_batch_id` ASC) VISIBLE,
  CONSTRAINT `fk_inbound_orders_employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inbound_orders_warehouse1`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `mydb`.`warehouses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inbound_orders_product_batches1`
    FOREIGN KEY (`product_batch_id`)
    REFERENCES `mydb`.`product_batches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`localities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`localities` ;

CREATE TABLE IF NOT EXISTS `mydb`.`localities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `locality_name` VARCHAR(255) NULL,
  `province_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sellers_provinces1_idx` (`province_id` ASC) VISIBLE,
  CONSTRAINT `fk_sellers_provinces1`
    FOREIGN KEY (`province_id`)
    REFERENCES `mydb`.`provinces` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`order_details` ;

CREATE TABLE IF NOT EXISTS `mydb`.`order_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `clean_liness_status` VARCHAR(255) NULL,
  `quantity` INT NULL,
  `temperature` INT NULL,
  `purchase_order_id` INT NOT NULL,
  `product_record_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_details_purchase_orders1_idx` (`purchase_order_id` ASC) VISIBLE,
  INDEX `fk_order_details_product_records1_idx` (`product_record_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_details_purchase_orders1`
    FOREIGN KEY (`purchase_order_id`)
    REFERENCES `mydb`.`purchase_orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_details_product_records1`
    FOREIGN KEY (`product_record_id`)
    REFERENCES `mydb`.`product_records` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`order_status` ;

CREATE TABLE IF NOT EXISTS `mydb`.`order_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_batches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product_batches` ;

CREATE TABLE IF NOT EXISTS `mydb`.`product_batches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `batch_number` VARCHAR(255) NOT NULL,
  `current_quantity` INT NULL,
  `current_temperature` INT NULL,
  `due_date` DATETIME NULL,
  `initial_quantity` INT NULL,
  `manufacturing_date` DATETIME NULL,
  `manufacturing_hour` DATETIME NULL,
  `minimun_temperature` INT NULL,
  `section_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_batches_sections1_idx` (`section_id` ASC) VISIBLE,
  UNIQUE INDEX `batch_number_UNIQUE` (`batch_number` ASC) VISIBLE,
  INDEX `fk_product_batches_products1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_batches_sections1`
    FOREIGN KEY (`section_id`)
    REFERENCES `mydb`.`sections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_batches_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_records`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product_records` ;

CREATE TABLE IF NOT EXISTS `mydb`.`product_records` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `last_update_date` DATETIME NULL,
  `purchase_price` INT NULL,
  `sale_price` INT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_records_products1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_records_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`products` ;

CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL,
  `expiration_rate` INT NULL,
  `freezing_rate` INT NULL,
  `height` INT NULL,
  `length` INT NULL,
  `net_weight` INT NULL,
  `product_code` VARCHAR(255) NOT NULL,
  `recommended_freezing_temperature` INT NULL,
  `width` INT NULL,
  `product_type_id` INT NOT NULL,
  `seller_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_product_types1_idx` (`product_type_id` ASC) VISIBLE,
  INDEX `fk_products_sellers1_idx` (`seller_id` ASC) VISIBLE,
  UNIQUE INDEX `product_code_UNIQUE` (`product_code` ASC) VISIBLE,
  CONSTRAINT `fk_products_product_types1`
    FOREIGN KEY (`product_type_id`)
    REFERENCES `mydb`.`product_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_sellers1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `mydb`.`sellers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product_types` ;

CREATE TABLE IF NOT EXISTS `mydb`.`product_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`provinces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`provinces` ;

CREATE TABLE IF NOT EXISTS `mydb`.`provinces` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `province_name` VARCHAR(255) NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_provinces_countries1_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_provinces_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`purchase_orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`purchase_orders` ;

CREATE TABLE IF NOT EXISTS `mydb`.`purchase_orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_number` VARCHAR(255) NULL,
  `order_date` DATETIME NULL,
  `tracking_code` VARCHAR(255) NULL,
  `buyer_id` INT NOT NULL,
  `order_status_id` INT NOT NULL,
  `carrier_id` INT NOT NULL,
  `warehouse_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_purchase_orders_buyers1_idx` (`buyer_id` ASC) VISIBLE,
  INDEX `fk_purchase_orders_order_status1_idx` (`order_status_id` ASC) VISIBLE,
  INDEX `fk_purchase_orders_carriers1_idx` (`carrier_id` ASC) VISIBLE,
  INDEX `fk_purchase_orders_warehouse1_idx` (`warehouse_id` ASC) VISIBLE,
  UNIQUE INDEX `order_number_UNIQUE` (`order_number` ASC) VISIBLE,
  UNIQUE INDEX `tracking_code_UNIQUE` (`tracking_code` ASC) VISIBLE,
  CONSTRAINT `fk_purchase_orders_buyers1`
    FOREIGN KEY (`buyer_id`)
    REFERENCES `mydb`.`buyers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_orders_order_status1`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `mydb`.`order_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_orders_carriers1`
    FOREIGN KEY (`carrier_id`)
    REFERENCES `mydb`.`carriers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_orders_warehouse1`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `mydb`.`warehouses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sections` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sections` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `section_number` INT NOT NULL,
  `current_capacity` INT NULL,
  `current_temperature` INT NULL,
  `maximun_capacity` INT NULL,
  `minimun_capacity` INT NULL,
  `minimun_temperature` INT NULL,
  `warehouse_id` INT NOT NULL,
  `product_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sections_warehouse1_idx` (`warehouse_id` ASC) VISIBLE,
  INDEX `fk_sections_product_types1_idx` (`product_type_id` ASC) VISIBLE,
  UNIQUE INDEX `section_number_UNIQUE` (`section_number` ASC) VISIBLE,
  CONSTRAINT `fk_sections_warehouse1`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `mydb`.`warehouses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sections_product_types1`
    FOREIGN KEY (`product_type_id`)
    REFERENCES `mydb`.`product_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sellers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sellers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sellers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cid` INT NOT NULL,
  `company_name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `telephone` VARCHAR(255) NOT NULL,
  `locality_id` INT NOT NULL,
  PRIMARY KEY (`id`, `cid`),
  INDEX `fk_sellers_localities1_idx` (`locality_id` ASC) VISIBLE,
  UNIQUE INDEX `cid_UNIQUE` (`cid` ASC) VISIBLE,
  CONSTRAINT `fk_sellers_localities1`
    FOREIGN KEY (`locality_id`)
    REFERENCES `mydb`.`localities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`warehouse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`warehouses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`warehouses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NULL,
  `locality_id` INT NOT NULL,
  `telephone` VARCHAR(255) NULL,
  `warehouse_code` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_warehouse_localities1_idx` (`locality_id` ASC) VISIBLE,
  UNIQUE INDEX `warehouse_code_UNIQUE` (`warehouse_code` ASC) VISIBLE,
  CONSTRAINT `fk_warehouse_localities1`
    FOREIGN KEY (`locality_id`)
    REFERENCES `mydb`.`localities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO mydb.countries (country_name) VALUES ('Argentina');
INSERT INTO mydb.countries (country_name) VALUES ('Colombia');
INSERT INTO mydb.provinces (province_name, country_id) VALUES ('Cordoba', 1);
INSERT INTO mydb.localities (locality_name,province_id) VALUES ('Rio Cuarto', 1);
INSERT INTO mydb.warehouses (address,locality_id, telephone, warehouse_code) VALUES ("Lavalle 467", 1, "38274324","23435");
INSERT INTO mydb.warehouses (address,locality_id, telephone, warehouse_code) VALUES ("Lavalle 467", 1, "38274324","123435");
INSERT INTO mydb.carriers (cid, company_name, address, telephone, locality_id) VALUES ("123", "Carry 1", "Lavalle 123","38274324","1");

-- Prerrequisites product batchs
INSERT INTO `mydb`.`product_types` (`description`) VALUES ("producto tipo 1");
INSERT INTO `mydb`.`sellers` (`cid`, `company_name`, `address`, `telephone`, `locality_id`) VALUES (1, "abc", "abc", 1, 1);
INSERT INTO `mydb`.`sections` (`section_number`, `current_capacity`, `current_temperature`, `maximun_capacity`, `minimun_capacity`, `minimun_temperature`, `warehouse_id`, `product_type_id`) VALUES (1, 1, 1, 1, 1, 1, 1, 1);
INSERT INTO `mydb`.`products` (`description`, `expiration_rate`, `freezing_rate`, `height`, `length`, `net_weight`, `product_code`, `recommended_freezing_temperature`, `width`, `product_type_id`, `seller_id`) VALUES ("abc", 1, 1, 1, 1, 1, "abc", 1, 1, 1, 1);

INSERT INTO `mydb`.`product_batches` (`batch_number`, `current_quantity`, `current_temperature`, `due_date`, `initial_quantity`, `manufacturing_date`, `manufacturing_hour`, `minimun_temperature`,`section_id`, `product_id`) VALUES
("abc", 1, 1, '2020-10-4', 1, '2020-10-4', '2020-10-4', 1, 1, 1);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;